name: Auto V2Ray Tester

on:
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: # 👈 این بخش را اضافه کنید تا ربات اجازه نوشتن داشته باشد
      contents: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Run Speed Test Script
      run: python main.py

    - name: Commit and Push Results
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add best_configs.txt
        git commit -m "Update top 20 configs" || exit 0
        git push
